Update README.md
When testing I was able to run only on Mongo 3.4.

Mongo v3.2

12:52:50.383 [http-bio-8080-exec-1] ERROR za.co.absa.spline.web.logging.ErrorCode$ - ErrorCode(69e0f1a9-670c-4b6a-81d5-56c830f77e5f)
com.mongodb.MongoCommandException: Command failed with error 16436: 'Unrecognized pipeline stage name: '$addFields'' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Unrecognized pipeline stage name: '$addFields'", "code" : 16436 }
	at com.mongodb.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:115)
	at com.mongodb.connection.CommandProtocol.execute(CommandProtocol.java:114)
	at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:159)
	at com.mongodb.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:286)
	at com.mongodb.connection.DefaultServerConnection.command(DefaultServerConnection.java:173)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:215)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:206)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:112)
	at com.mongodb.operation.AggregateOperation$1.call(AggregateOperation.java:227)
	at com.mongodb.operation.AggregateOperation$1.call(AggregateOperation.java:223)
	at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:239)
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:212)
	at com.mongodb.operation.AggregateOperation.execute(AggregateOperation.java:223)
	at com.mongodb.operation.AggregateOperation.execute(AggregateOperation.java:65)
	at com.mongodb.Mongo.execute(Mongo.java:772)
	at com.mongodb.Mongo$2.execute(Mongo.java:759)
	at com.mongodb.DBCollection.aggregate(DBCollection.java:1377)
	at com.mongodb.DBCollection.aggregate(DBCollection.java:1308)
	at com.mongodb.DBCollection.aggregate(DBCollection.java:1294)
	at za.co.absa.spline.persistence.mongo.MongoDataLineageReader$$anonfun$za$co$absa$spline$persistence$mongo$MongoDataLineageReader$$selectPersistedDatasets$1.apply(MongoDataLineageReader.scala:187)
	at za.co.absa.spline.persistence.mongo.MongoDataLineageReader$$anonfun$za$co$absa$spline$persistence$mongo$MongoDataLineageReader$$selectPersistedDatasets$1.apply(MongoDataLineageReader.scala:188)
	at scala.concurrent.impl.ExecutionContextImpl$DefaultThreadFactory$$anon$2$$anon$4.block(ExecutionContextImpl.scala:48)
	at scala.concurrent.forkjoin.ForkJoinPool.managedBlock(ForkJoinPool.java:3640)
	at scala.concurrent.impl.ExecutionContextImpl$DefaultThreadFactory$$anon$2.blockOn(ExecutionContextImpl.scala:45)
	at scala.concurrent.package$.blocking(package.scala:123)
	at za.co.absa.spline.persistence.mongo.MongoDataLineageReader.za$co$absa$spline$persistence$mongo$MongoDataLineageReader$$selectPersistedDatasets(MongoDataLineageReader.scala:188)
	at za.co.absa.spline.persistence.mongo.MongoDataLineageReader$$anonfun$list$1.apply(MongoDataLineageReader.scala:170)
	at za.co.absa.spline.persistence.mongo.MongoDataLineageReader$$anonfun$list$1.apply(MongoDataLineageReader.scala:170)


Mongo v3.6

13:52:55.114 [http-bio-8080-exec-6] ERROR za.co.absa.spline.web.logging.ErrorCode$ - ErrorCode(7fbccf0c-7fb5-4883-ac9f-14af8ca9576e)
com.mongodb.MongoCommandException: Command failed with error 9: 'The 'cursor' option is required, except for aggregate with the explain argument' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "The 'cursor' option is required, except for aggregate with the explain argument", "code" : 9, "codeName" : "FailedToParse" }
	at com.mongodb.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:115)
	at com.mongodb.connection.CommandProtocol.execute(CommandProtocol.java:114)
	at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:159)
	at com.mongodb.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:286)
	at com.mongodb.connection.DefaultServerConnection.command(DefaultServerConnection.java:173)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:215)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:206)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:112)
	at com.mongodb.operation.AggregateOperation$1.call(AggregateOperation.java:227)
	at com.mongodb.operation.AggregateOperation$1.call(AggregateOperation.java:223)
	at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:239)
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:212)
	at com.mongodb.operation.AggregateOperation.execute(AggregateOperation.java:223)
	at com.mongodb.operation.AggregateOperation.execute(AggregateOperation.java:65)
	at com.mongodb.Mongo.execute(Mongo.java:772)
	at com.mongodb.Mongo$2.execute(Mongo.java:759)
	at com.mongodb.DBCollection.aggregate(DBCollection.java:1377)
	at com.mongodb.DBCollection.aggregate(DBCollection.java:1308)
	at com.mongodb.DBCollection.aggregate(DBCollection.java:1294)
	at za.co.absa.spline.persistence.mongo.MongoDataLineageReader$$anonfun$za$co$absa$spline$persistence$mongo$MongoDataLineageReader$$selectPersistedDatasets$1.apply(MongoDataLineageReader.scala:187)
	at za.co.absa.spline.persistence.mongo.MongoDataLineageReader$$anonfun$za$co$absa$spline$persistence$mongo$MongoDataLineageReader$$selectPersistedDatasets$1.apply(MongoDataLineageReader.scala:188)
	at scala.concurrent.impl.ExecutionContextImpl$DefaultThreadFactory$$anon$2$$anon$4.block(ExecutionContextImpl.scala:48)
	at scala.concurrent.forkjoin.ForkJoinPool.managedBlock(ForkJoinPool.java:3640)
	at scala.concurrent.impl.ExecutionContextImpl$DefaultThreadFactory$$anon$2.blockOn(ExecutionContextImpl.scala:45)
	at scala.concurrent.package$.blocking(package.scala:123)
	at za.co.absa.spline.persistence.mongo.MongoDataLineageReader.za$co$absa$spline$persistence$mongo$MongoDataLineageReader$$selectPersistedDatasets(MongoDataLineageReader.scala:188)
	at za.co.absa.spline.persistence.mongo.MongoDataLineageReader$$anonfun$list$1.apply(MongoDataLineageReader.scala:170)
	at za.co.absa.spline.persistence.mongo.MongoDataLineageReader$$anonfun$list$1.apply(MongoDataLineageReader.scala:170)